# Real end-to-end integration test for Colors extension with @cardmeta blocks

using Test
using OhMyCards
using Colors
using Documenter

@testset "Colors Extension - Full End-to-End Integration" begin
    @testset "Complete Documenter build with color matrix covers and gallery" begin
        mktempdir() do tmpdir
            src_dir = joinpath(tmpdir, "src")
            examples_dir = joinpath(src_dir, "examples")
            mkpath(examples_dir)

            # Create index page with overview gallery
            write(
                joinpath(src_dir, "index.md"),
                """
# Test Documentation

This is a test documentation site with color matrix cover images.

## Example Gallery

```@overviewgallery
gradient_example
checkerboard_example
rainbow_example
```
"""
            )

            # Create example 1: Gradient image
            write(
                joinpath(examples_dir, "gradient_example.md"),
                """
```@cardmeta
Title = "Gradient Example"
Description = "A simple gradient color matrix"
Cover = gradient
```

# Gradient Example

This example demonstrates a gradient color matrix as a cover image.

```@example gradient_example
using Colors

# Create a gradient
gradient = [RGB(i/100, j/100, 0.5) for i in 1:100, j in 1:100]
```
"""
            )

            # Create example 2: Checkerboard pattern
            write(
                joinpath(examples_dir, "checkerboard_example.md"),
                """
```@cardmeta
Title = "Checkerboard Pattern"
Description = "A checkerboard pattern using color matrices"
Cover = checkerboard
```

# Checkerboard Example

This example shows a checkerboard pattern.

```@example checkerboard_example
using Colors

# Create checkerboard
checkerboard = [((i÷10 + j÷10) % 2 == 0) ? RGB(1.0, 1.0, 1.0) : RGB(0.0, 0.0, 0.0) for i in 1:80, j in 1:80]
```
"""
            )

            # Create example 3: Rainbow colors
            write(
                joinpath(examples_dir, "rainbow_example.md"),
                """
```@cardmeta
Title = "Rainbow Colors"
Description = "A rainbow color spectrum"
Cover = rainbow
```

# Rainbow Example

This example demonstrates HSV color space with a rainbow.

```@example rainbow_example
using Colors

# Create rainbow
rainbow = RGB[HSV(360 * j/120, 1.0, 1.0) for i in 1:60, j in 1:120]
```
"""
            )

            # Build the documentation with ExampleConfig plugin
            build_dir = joinpath(tmpdir, "build")
            doc = makedocs(
                sitename="Color Matrix Test",
                source=src_dir,
                build=build_dir,
                format=Documenter.HTML(prettyurls=false, edit_link=nothing),
                plugins=[ExampleConfig()],
                pages=[
                    "Home" => "index.md",
                    "Examples" => [
                        "examples/gradient_example.md",
                        "examples/checkerboard_example.md",
                        "examples/rainbow_example.md",
                    ]
                ],
                debug=true,
                warnonly=false,
            )

            # Verify the build succeeded
            @test doc isa Documenter.Document

            # Verify HTML files were created
            @test isfile(joinpath(build_dir, "index.html"))
            @test isfile(joinpath(build_dir, "examples", "gradient_example.html"))
            @test isfile(joinpath(build_dir, "examples", "checkerboard_example.html"))
            @test isfile(joinpath(build_dir, "examples", "rainbow_example.html"))

            # Read the index.html to verify gallery was generated
            index_html = read(joinpath(build_dir, "index.html"), String)

            # Verify gallery contains our examples
            @test occursin("Gradient Example", index_html)
            @test occursin("Checkerboard Pattern", index_html)
            @test occursin("Rainbow Colors", index_html)

            # Verify cover images were generated by checking the HTML contains PNG references
            # The PNGs are embedded directly in the HTML with relative paths like ../HASH.png or ./HASH.png
            png_matches = collect(eachmatch(r"(?:\.\./|\./)[A-Za-z0-9]+\.png", index_html))

            # Should have at least 3 PNG references (one for each example)
            @test length(png_matches) >= 3

            # Verify gallery HTML structure (uses grid-container, not gallerybox)
            @test occursin("grid-container", index_html) || occursin("gallery", index_html)

            # Verify PNG references in the gallery (they're embedded in the HTML)
            @test occursin(".png", index_html)
        end
    end

    @testset "Color matrix covers with prettyurls enabled" begin
        mktempdir() do tmpdir
            src_dir = joinpath(tmpdir, "src")
            examples_dir = joinpath(src_dir, "examples")
            mkpath(examples_dir)

            # Create simple index
            write(
                joinpath(src_dir, "index.md"),
                """
# Test Site

```@overviewgallery
color_test
```
"""
            )

            # Create one example with color matrix
            write(
                joinpath(examples_dir, "color_test.md"),
                """
```@cardmeta
Title = "Color Test"
Description = "Testing color matrices with prettyurls"
Cover = cover
```

# Color Test

Testing prettyurls with color matrix covers.

```@example color_test
using Colors
cover = [RGB(i/50, j/50, 0.8) for i in 1:50, j in 1:50]
```
"""
            )

            # Build with prettyurls=true
            build_dir = joinpath(tmpdir, "build")
            doc = makedocs(
                sitename="PrettyURLs Test",
                source=src_dir,
                build=build_dir,
                format=Documenter.HTML(prettyurls=true, edit_link=nothing),
                plugins=[ExampleConfig()],
                pages=[
                    "Home" => "index.md",
                    "Examples" => ["examples/color_test.md"]
                ],
                debug=true,
                warnonly=false,
            )

            # With prettyurls, pages are in subdirectories
            @test isfile(joinpath(build_dir, "index.html"))
            @test isfile(joinpath(build_dir, "examples", "color_test", "index.html"))

            # Verify PNG reference exists in the HTML
            index_html = read(joinpath(build_dir, "index.html"), String)
            @test occursin(".png", index_html)
        end
    end
end
